### ISSUE TITLE
White border surrounding card when used in grid

### ISSUE THREAD

**Issue by ukmgranger** [GeorgeSG/lovelace-time-picker-card#18]
### Checklist:

- [Y] I updated to the latest version available
- [Y] I cleared the cache of my browser

### The problem
There is a white border around the edge of the card when using it in a grid.

### Environment

Running on Proxmox:
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4796
Installed Version | 1.11.3
Stage | running
Available Repositories | 776
Installed Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 28 April 2021, 1:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 62.3 GB
disk_used | 12.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), deCONZ (6.8.0), Terminal & SSH (9.1.0), Node-RED (8.2.0), File editor (5.2.0), Hass.io Google Drive Backup (0.52), Almond (1.1.2), AirCast (3.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 18
views | 17
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

- time-picker-card release with the issue:
- Last working time-picker-card release (if known):
- Browser and Operating System:

### Problem-relevant configuration

```yaml

```

### Javascript errors shown in the web inspector (if applicable):

```

```
![Screenshot 2021-03-29 at 16 51 51](https://user-images.githubusercontent.com/35274652/112864648-ec1e0900-90af-11eb-88a8-bc2f8b6c9999.png)

**Comment by julienlarivee** [comment]
I got it too. 
Your white border seems to be scroll bars.

![image](https://user-images.githubusercontent.com/55027006/113049871-264fdf00-9172-11eb-8e6b-3e907c84bb8f.png)

**Comment by jszust** [comment]
I'm having the same issue

**Comment by GeorgeSG** [comment]
Thanks for the bug report, folks! I just released version 1.2.1 which hopefully addresses the issue.

Scrollbars will still be necessary sometimes, due to how the card fits inside a grid. But at least when they are not needed, they shouldn't be visible now.

**Comment by riopedre** [comment]
After updating to 1.2.1, I have the same issue. I'm not using grid card.
![imagen](https://user-images.githubusercontent.com/20193450/113189904-0399f500-925c-11eb-9f73-ac7af8e23dba.png)

**Comment by GeorgeSG** [comment]
@riopedre please try hard reloading the page and/or clearing your browser's cache :)

**Comment by riopedre** [comment]
After uploading and before sending a message, I have reloaded the page with no changes. After that, I have cleared the browser cache and reloaded the page again with no changes. And I have restarted Home Assistant and I have repeated the browser cache cleaning and the reloading of the page with no changes.
Then, while I was writing this answer, I have reloaded the page a last time before sending the message and it works!
Sorry for the noise. And thank you very much for your work.

**Comment by JDunnio** [comment]
Thanks for squashing this bug. Had problems in MS Edge browser where it wasn't fixed.

After testing with a Inprivate tab and seeing that is was fixed, i cleared my cache (all not just last day) and it as fixed.

Thanks again! Loving it!

![image](https://user-images.githubusercontent.com/44028885/113264980-e6a10880-92d3-11eb-83f7-f4df82e8ae01.png)
